services:
  postgres:
    build:
      context: .
      target: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secrect
      - POSTGRES_DB=geo-projects-platform
    networks:
      - geo-projects-platform

  cli:
    build:
      context: .
      target: cli
    environment:
      - NODE_ENV=development
    networks:
      - geo-projects-platform
    volumes:
      - .:/geo-projects-platform
    develop:
      watch:
        - action: sync
          path: .
          target: /geo-projects-platform

networks:
  geo-projects-platform:
    driver: bridge
