services:
  database-postgres:
    build:
      context: .
      target: database-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secrect
      - POSTGRES_DB=geo-projects-platform
    networks:
      - geo-projects-platform

  service-api:
    build:
      context: .
      target: app-service-api
    environment:
      - NODE_ENV=development
    networks:
      - geo-projects-platform
    ports:
      - "3000:3000"
    volumes:
      - .:/geo-projects-platform
    env_file:
      - .env

  cli:
    build:
      context: .
      target: cli
    environment:
      - NODE_ENV=development
    networks:
      - geo-projects-platform
    volumes:
      - .:/geo-projects-platform
    develop:
      watch:
        - action: sync
          path: .
          target: /geo-projects-platform
    env_file:
      - .env

networks:
  geo-projects-platform:
    driver: bridge
