name: Continuous Integration

on:
  push:
    branches:
      - "*"

jobs:
  prepare:
    name: Lint and Build
    runs-on: ubuntu-22.04
    concurrency:
      group: ci-branch-${{ github.ref_name }}
      cancel-in-progress: true

    env:
      TURBO_TELEMETRY_DISABLED: 1

    steps:
      - id: repository-checkout
        name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - id: setup-pnpm
        name: Setup dependency manager
        uses: pnpm/action-setup@v4

      - id: setup-node
        name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "pnpm"

      - id: configure-pnpm
        name: Configure dependency manager
        run: pnpm config set global-bin-dir /usr/local/bin/

      - id: install-dependencies
        name: Install dependencies
        run: pnpm install

      - id: run-lint
        name: Run lint
        run: pnpm run lint

      - id: run-build
        name: Run build
        run: pnpm run build

  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    concurrency:
      group: ci-branch-${{ github.ref_name }}
      cancel-in-progress: true

    needs:
      - prepare

    steps:
      - id: repository-checkout
        name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - id: prepare-deploy-cli
        name: Prepare Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - id: run-deploy
        name: Run Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy . --app geo-projects-service-api
